# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: V40 | An Independent Software Consultant Company
email: info@v40.io
description: > # this means to ignore newlines until "baseurl:"
  An Independent Software Consulting company specializing in ruby, elixir and js.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://v40.io"
twitter_username: iamkristian
github_username:  iamkristian

exclude:
  - "bower.json"
  - ".bowerrc"
encoding: "utf-8"

# Conversion
markdown: kramdown
highlighter: rouge
sass:
  style: :compressed


kramdown:
    input: GFM
